// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/robocar.proto

package justine.robocar;

public final class TrafficStateProtos {
  private TrafficStateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CarDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required fixed64 node_from = 1;
    /**
     * <code>required fixed64 node_from = 1;</code>
     */
    boolean hasNodeFrom();
    /**
     * <code>required fixed64 node_from = 1;</code>
     */
    long getNodeFrom();

    // required fixed64 node_to = 2;
    /**
     * <code>required fixed64 node_to = 2;</code>
     */
    boolean hasNodeTo();
    /**
     * <code>required fixed64 node_to = 2;</code>
     */
    long getNodeTo();

    // required fixed64 max_step = 3;
    /**
     * <code>required fixed64 max_step = 3;</code>
     */
    boolean hasMaxStep();
    /**
     * <code>required fixed64 max_step = 3;</code>
     */
    long getMaxStep();

    // required fixed64 step = 4;
    /**
     * <code>required fixed64 step = 4;</code>
     */
    boolean hasStep();
    /**
     * <code>required fixed64 step = 4;</code>
     */
    long getStep();

    // required .justine.robocar.CarData.ProtoCarType type = 5;
    /**
     * <code>required .justine.robocar.CarData.ProtoCarType type = 5;</code>
     */
    boolean hasType();
    /**
     * <code>required .justine.robocar.CarData.ProtoCarType type = 5;</code>
     */
    justine.robocar.TrafficStateProtos.CarData.ProtoCarType getType();

    // optional int32 caught = 6;
    /**
     * <code>optional int32 caught = 6;</code>
     */
    boolean hasCaught();
    /**
     * <code>optional int32 caught = 6;</code>
     */
    int getCaught();

    // optional string team = 7;
    /**
     * <code>optional string team = 7;</code>
     */
    boolean hasTeam();
    /**
     * <code>optional string team = 7;</code>
     */
    java.lang.String getTeam();
    /**
     * <code>optional string team = 7;</code>
     */
    com.google.protobuf.ByteString
        getTeamBytes();

    // optional int32 id = 8;
    /**
     * <code>optional int32 id = 8;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 8;</code>
     */
    int getId();

    // optional int32 size = 9;
    /**
     * <code>optional int32 size = 9;</code>
     */
    boolean hasSize();
    /**
     * <code>optional int32 size = 9;</code>
     */
    int getSize();

    // repeated fixed64 path = 10;
    /**
     * <code>repeated fixed64 path = 10;</code>
     */
    java.util.List<java.lang.Long> getPathList();
    /**
     * <code>repeated fixed64 path = 10;</code>
     */
    int getPathCount();
    /**
     * <code>repeated fixed64 path = 10;</code>
     */
    long getPath(int index);
  }
  /**
   * Protobuf type {@code justine.robocar.CarData}
   */
  public static final class CarData extends
      com.google.protobuf.GeneratedMessage
      implements CarDataOrBuilder {
    // Use CarData.newBuilder() to construct.
    private CarData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CarData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CarData defaultInstance;
    public static CarData getDefaultInstance() {
      return defaultInstance;
    }

    public CarData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CarData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              nodeFrom_ = input.readFixed64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              nodeTo_ = input.readFixed64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              maxStep_ = input.readFixed64();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              step_ = input.readFixed64();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              justine.robocar.TrafficStateProtos.CarData.ProtoCarType value = justine.robocar.TrafficStateProtos.CarData.ProtoCarType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                type_ = value;
              }
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              caught_ = input.readInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              team_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              id_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              size_ = input.readInt32();
              break;
            }
            case 81: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                path_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000200;
              }
              path_.add(input.readFixed64());
              break;
            }
            case 82: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200) && input.getBytesUntilLimit() > 0) {
                path_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000200;
              }
              while (input.getBytesUntilLimit() > 0) {
                path_.add(input.readFixed64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          path_ = java.util.Collections.unmodifiableList(path_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return justine.robocar.TrafficStateProtos.internal_static_justine_robocar_CarData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return justine.robocar.TrafficStateProtos.internal_static_justine_robocar_CarData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              justine.robocar.TrafficStateProtos.CarData.class, justine.robocar.TrafficStateProtos.CarData.Builder.class);
    }

    public static com.google.protobuf.Parser<CarData> PARSER =
        new com.google.protobuf.AbstractParser<CarData>() {
      public CarData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CarData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CarData> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code justine.robocar.CarData.ProtoCarType}
     */
    public enum ProtoCarType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NORMAL = 0;</code>
       */
      NORMAL(0, 0),
      /**
       * <code>POLICE = 1;</code>
       */
      POLICE(1, 1),
      /**
       * <code>GANGSTER = 2;</code>
       */
      GANGSTER(2, 2),
      /**
       * <code>CAUGHT = 3;</code>
       */
      CAUGHT(3, 3),
      /**
       * <code>PEDESTRIAN = 4;</code>
       */
      PEDESTRIAN(4, 4),
      ;

      /**
       * <code>NORMAL = 0;</code>
       */
      public static final int NORMAL_VALUE = 0;
      /**
       * <code>POLICE = 1;</code>
       */
      public static final int POLICE_VALUE = 1;
      /**
       * <code>GANGSTER = 2;</code>
       */
      public static final int GANGSTER_VALUE = 2;
      /**
       * <code>CAUGHT = 3;</code>
       */
      public static final int CAUGHT_VALUE = 3;
      /**
       * <code>PEDESTRIAN = 4;</code>
       */
      public static final int PEDESTRIAN_VALUE = 4;


      public final int getNumber() { return value; }

      public static ProtoCarType valueOf(int value) {
        switch (value) {
          case 0: return NORMAL;
          case 1: return POLICE;
          case 2: return GANGSTER;
          case 3: return CAUGHT;
          case 4: return PEDESTRIAN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ProtoCarType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ProtoCarType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ProtoCarType>() {
              public ProtoCarType findValueByNumber(int number) {
                return ProtoCarType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return justine.robocar.TrafficStateProtos.CarData.getDescriptor().getEnumTypes().get(0);
      }

      private static final ProtoCarType[] VALUES = values();

      public static ProtoCarType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ProtoCarType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:justine.robocar.CarData.ProtoCarType)
    }

    private int bitField0_;
    // required fixed64 node_from = 1;
    public static final int NODE_FROM_FIELD_NUMBER = 1;
    private long nodeFrom_;
    /**
     * <code>required fixed64 node_from = 1;</code>
     */
    public boolean hasNodeFrom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required fixed64 node_from = 1;</code>
     */
    public long getNodeFrom() {
      return nodeFrom_;
    }

    // required fixed64 node_to = 2;
    public static final int NODE_TO_FIELD_NUMBER = 2;
    private long nodeTo_;
    /**
     * <code>required fixed64 node_to = 2;</code>
     */
    public boolean hasNodeTo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required fixed64 node_to = 2;</code>
     */
    public long getNodeTo() {
      return nodeTo_;
    }

    // required fixed64 max_step = 3;
    public static final int MAX_STEP_FIELD_NUMBER = 3;
    private long maxStep_;
    /**
     * <code>required fixed64 max_step = 3;</code>
     */
    public boolean hasMaxStep() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required fixed64 max_step = 3;</code>
     */
    public long getMaxStep() {
      return maxStep_;
    }

    // required fixed64 step = 4;
    public static final int STEP_FIELD_NUMBER = 4;
    private long step_;
    /**
     * <code>required fixed64 step = 4;</code>
     */
    public boolean hasStep() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required fixed64 step = 4;</code>
     */
    public long getStep() {
      return step_;
    }

    // required .justine.robocar.CarData.ProtoCarType type = 5;
    public static final int TYPE_FIELD_NUMBER = 5;
    private justine.robocar.TrafficStateProtos.CarData.ProtoCarType type_;
    /**
     * <code>required .justine.robocar.CarData.ProtoCarType type = 5;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .justine.robocar.CarData.ProtoCarType type = 5;</code>
     */
    public justine.robocar.TrafficStateProtos.CarData.ProtoCarType getType() {
      return type_;
    }

    // optional int32 caught = 6;
    public static final int CAUGHT_FIELD_NUMBER = 6;
    private int caught_;
    /**
     * <code>optional int32 caught = 6;</code>
     */
    public boolean hasCaught() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 caught = 6;</code>
     */
    public int getCaught() {
      return caught_;
    }

    // optional string team = 7;
    public static final int TEAM_FIELD_NUMBER = 7;
    private java.lang.Object team_;
    /**
     * <code>optional string team = 7;</code>
     */
    public boolean hasTeam() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string team = 7;</code>
     */
    public java.lang.String getTeam() {
      java.lang.Object ref = team_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          team_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string team = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTeamBytes() {
      java.lang.Object ref = team_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        team_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 id = 8;
    public static final int ID_FIELD_NUMBER = 8;
    private int id_;
    /**
     * <code>optional int32 id = 8;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 id = 8;</code>
     */
    public int getId() {
      return id_;
    }

    // optional int32 size = 9;
    public static final int SIZE_FIELD_NUMBER = 9;
    private int size_;
    /**
     * <code>optional int32 size = 9;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 size = 9;</code>
     */
    public int getSize() {
      return size_;
    }

    // repeated fixed64 path = 10;
    public static final int PATH_FIELD_NUMBER = 10;
    private java.util.List<java.lang.Long> path_;
    /**
     * <code>repeated fixed64 path = 10;</code>
     */
    public java.util.List<java.lang.Long>
        getPathList() {
      return path_;
    }
    /**
     * <code>repeated fixed64 path = 10;</code>
     */
    public int getPathCount() {
      return path_.size();
    }
    /**
     * <code>repeated fixed64 path = 10;</code>
     */
    public long getPath(int index) {
      return path_.get(index);
    }

    private void initFields() {
      nodeFrom_ = 0L;
      nodeTo_ = 0L;
      maxStep_ = 0L;
      step_ = 0L;
      type_ = justine.robocar.TrafficStateProtos.CarData.ProtoCarType.NORMAL;
      caught_ = 0;
      team_ = "";
      id_ = 0;
      size_ = 0;
      path_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNodeFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodeTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxStep()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStep()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, nodeFrom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, nodeTo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFixed64(3, maxStep_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFixed64(4, step_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, type_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, caught_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTeamBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, id_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, size_);
      }
      for (int i = 0; i < path_.size(); i++) {
        output.writeFixed64(10, path_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, nodeFrom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, nodeTo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, maxStep_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(4, step_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, caught_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTeamBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, id_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, size_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getPathList().size();
        size += dataSize;
        size += 1 * getPathList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static justine.robocar.TrafficStateProtos.CarData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static justine.robocar.TrafficStateProtos.CarData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static justine.robocar.TrafficStateProtos.CarData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static justine.robocar.TrafficStateProtos.CarData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static justine.robocar.TrafficStateProtos.CarData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static justine.robocar.TrafficStateProtos.CarData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static justine.robocar.TrafficStateProtos.CarData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static justine.robocar.TrafficStateProtos.CarData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static justine.robocar.TrafficStateProtos.CarData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static justine.robocar.TrafficStateProtos.CarData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(justine.robocar.TrafficStateProtos.CarData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code justine.robocar.CarData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements justine.robocar.TrafficStateProtos.CarDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return justine.robocar.TrafficStateProtos.internal_static_justine_robocar_CarData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return justine.robocar.TrafficStateProtos.internal_static_justine_robocar_CarData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                justine.robocar.TrafficStateProtos.CarData.class, justine.robocar.TrafficStateProtos.CarData.Builder.class);
      }

      // Construct using justine.robocar.TrafficStateProtos.CarData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nodeFrom_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeTo_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        maxStep_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        step_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = justine.robocar.TrafficStateProtos.CarData.ProtoCarType.NORMAL;
        bitField0_ = (bitField0_ & ~0x00000010);
        caught_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        team_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        path_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return justine.robocar.TrafficStateProtos.internal_static_justine_robocar_CarData_descriptor;
      }

      public justine.robocar.TrafficStateProtos.CarData getDefaultInstanceForType() {
        return justine.robocar.TrafficStateProtos.CarData.getDefaultInstance();
      }

      public justine.robocar.TrafficStateProtos.CarData build() {
        justine.robocar.TrafficStateProtos.CarData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public justine.robocar.TrafficStateProtos.CarData buildPartial() {
        justine.robocar.TrafficStateProtos.CarData result = new justine.robocar.TrafficStateProtos.CarData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeFrom_ = nodeFrom_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nodeTo_ = nodeTo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maxStep_ = maxStep_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.step_ = step_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.caught_ = caught_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.team_ = team_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.size_ = size_;
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          path_ = java.util.Collections.unmodifiableList(path_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.path_ = path_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof justine.robocar.TrafficStateProtos.CarData) {
          return mergeFrom((justine.robocar.TrafficStateProtos.CarData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(justine.robocar.TrafficStateProtos.CarData other) {
        if (other == justine.robocar.TrafficStateProtos.CarData.getDefaultInstance()) return this;
        if (other.hasNodeFrom()) {
          setNodeFrom(other.getNodeFrom());
        }
        if (other.hasNodeTo()) {
          setNodeTo(other.getNodeTo());
        }
        if (other.hasMaxStep()) {
          setMaxStep(other.getMaxStep());
        }
        if (other.hasStep()) {
          setStep(other.getStep());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCaught()) {
          setCaught(other.getCaught());
        }
        if (other.hasTeam()) {
          bitField0_ |= 0x00000040;
          team_ = other.team_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (!other.path_.isEmpty()) {
          if (path_.isEmpty()) {
            path_ = other.path_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensurePathIsMutable();
            path_.addAll(other.path_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNodeFrom()) {
          
          return false;
        }
        if (!hasNodeTo()) {
          
          return false;
        }
        if (!hasMaxStep()) {
          
          return false;
        }
        if (!hasStep()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        justine.robocar.TrafficStateProtos.CarData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (justine.robocar.TrafficStateProtos.CarData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required fixed64 node_from = 1;
      private long nodeFrom_ ;
      /**
       * <code>required fixed64 node_from = 1;</code>
       */
      public boolean hasNodeFrom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed64 node_from = 1;</code>
       */
      public long getNodeFrom() {
        return nodeFrom_;
      }
      /**
       * <code>required fixed64 node_from = 1;</code>
       */
      public Builder setNodeFrom(long value) {
        bitField0_ |= 0x00000001;
        nodeFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 node_from = 1;</code>
       */
      public Builder clearNodeFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeFrom_ = 0L;
        onChanged();
        return this;
      }

      // required fixed64 node_to = 2;
      private long nodeTo_ ;
      /**
       * <code>required fixed64 node_to = 2;</code>
       */
      public boolean hasNodeTo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required fixed64 node_to = 2;</code>
       */
      public long getNodeTo() {
        return nodeTo_;
      }
      /**
       * <code>required fixed64 node_to = 2;</code>
       */
      public Builder setNodeTo(long value) {
        bitField0_ |= 0x00000002;
        nodeTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 node_to = 2;</code>
       */
      public Builder clearNodeTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeTo_ = 0L;
        onChanged();
        return this;
      }

      // required fixed64 max_step = 3;
      private long maxStep_ ;
      /**
       * <code>required fixed64 max_step = 3;</code>
       */
      public boolean hasMaxStep() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required fixed64 max_step = 3;</code>
       */
      public long getMaxStep() {
        return maxStep_;
      }
      /**
       * <code>required fixed64 max_step = 3;</code>
       */
      public Builder setMaxStep(long value) {
        bitField0_ |= 0x00000004;
        maxStep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 max_step = 3;</code>
       */
      public Builder clearMaxStep() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxStep_ = 0L;
        onChanged();
        return this;
      }

      // required fixed64 step = 4;
      private long step_ ;
      /**
       * <code>required fixed64 step = 4;</code>
       */
      public boolean hasStep() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required fixed64 step = 4;</code>
       */
      public long getStep() {
        return step_;
      }
      /**
       * <code>required fixed64 step = 4;</code>
       */
      public Builder setStep(long value) {
        bitField0_ |= 0x00000008;
        step_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 step = 4;</code>
       */
      public Builder clearStep() {
        bitField0_ = (bitField0_ & ~0x00000008);
        step_ = 0L;
        onChanged();
        return this;
      }

      // required .justine.robocar.CarData.ProtoCarType type = 5;
      private justine.robocar.TrafficStateProtos.CarData.ProtoCarType type_ = justine.robocar.TrafficStateProtos.CarData.ProtoCarType.NORMAL;
      /**
       * <code>required .justine.robocar.CarData.ProtoCarType type = 5;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .justine.robocar.CarData.ProtoCarType type = 5;</code>
       */
      public justine.robocar.TrafficStateProtos.CarData.ProtoCarType getType() {
        return type_;
      }
      /**
       * <code>required .justine.robocar.CarData.ProtoCarType type = 5;</code>
       */
      public Builder setType(justine.robocar.TrafficStateProtos.CarData.ProtoCarType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .justine.robocar.CarData.ProtoCarType type = 5;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = justine.robocar.TrafficStateProtos.CarData.ProtoCarType.NORMAL;
        onChanged();
        return this;
      }

      // optional int32 caught = 6;
      private int caught_ ;
      /**
       * <code>optional int32 caught = 6;</code>
       */
      public boolean hasCaught() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 caught = 6;</code>
       */
      public int getCaught() {
        return caught_;
      }
      /**
       * <code>optional int32 caught = 6;</code>
       */
      public Builder setCaught(int value) {
        bitField0_ |= 0x00000020;
        caught_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 caught = 6;</code>
       */
      public Builder clearCaught() {
        bitField0_ = (bitField0_ & ~0x00000020);
        caught_ = 0;
        onChanged();
        return this;
      }

      // optional string team = 7;
      private java.lang.Object team_ = "";
      /**
       * <code>optional string team = 7;</code>
       */
      public boolean hasTeam() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string team = 7;</code>
       */
      public java.lang.String getTeam() {
        java.lang.Object ref = team_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          team_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string team = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTeamBytes() {
        java.lang.Object ref = team_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          team_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string team = 7;</code>
       */
      public Builder setTeam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        team_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string team = 7;</code>
       */
      public Builder clearTeam() {
        bitField0_ = (bitField0_ & ~0x00000040);
        team_ = getDefaultInstance().getTeam();
        onChanged();
        return this;
      }
      /**
       * <code>optional string team = 7;</code>
       */
      public Builder setTeamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        team_ = value;
        onChanged();
        return this;
      }

      // optional int32 id = 8;
      private int id_ ;
      /**
       * <code>optional int32 id = 8;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 id = 8;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 8;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000080;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 8;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional int32 size = 9;
      private int size_ ;
      /**
       * <code>optional int32 size = 9;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 size = 9;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>optional int32 size = 9;</code>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000100;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 size = 9;</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000100);
        size_ = 0;
        onChanged();
        return this;
      }

      // repeated fixed64 path = 10;
      private java.util.List<java.lang.Long> path_ = java.util.Collections.emptyList();
      private void ensurePathIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          path_ = new java.util.ArrayList<java.lang.Long>(path_);
          bitField0_ |= 0x00000200;
         }
      }
      /**
       * <code>repeated fixed64 path = 10;</code>
       */
      public java.util.List<java.lang.Long>
          getPathList() {
        return java.util.Collections.unmodifiableList(path_);
      }
      /**
       * <code>repeated fixed64 path = 10;</code>
       */
      public int getPathCount() {
        return path_.size();
      }
      /**
       * <code>repeated fixed64 path = 10;</code>
       */
      public long getPath(int index) {
        return path_.get(index);
      }
      /**
       * <code>repeated fixed64 path = 10;</code>
       */
      public Builder setPath(
          int index, long value) {
        ensurePathIsMutable();
        path_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated fixed64 path = 10;</code>
       */
      public Builder addPath(long value) {
        ensurePathIsMutable();
        path_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated fixed64 path = 10;</code>
       */
      public Builder addAllPath(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensurePathIsMutable();
        super.addAll(values, path_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated fixed64 path = 10;</code>
       */
      public Builder clearPath() {
        path_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:justine.robocar.CarData)
    }

    static {
      defaultInstance = new CarData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:justine.robocar.CarData)
  }

  public interface TrafficStateHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 time_minutes = 1;
    /**
     * <code>required int32 time_minutes = 1;</code>
     */
    boolean hasTimeMinutes();
    /**
     * <code>required int32 time_minutes = 1;</code>
     */
    int getTimeMinutes();

    // required int32 time_elapsed = 2;
    /**
     * <code>required int32 time_elapsed = 2;</code>
     */
    boolean hasTimeElapsed();
    /**
     * <code>required int32 time_elapsed = 2;</code>
     */
    int getTimeElapsed();

    // required int32 num_cars = 3;
    /**
     * <code>required int32 num_cars = 3;</code>
     */
    boolean hasNumCars();
    /**
     * <code>required int32 num_cars = 3;</code>
     */
    int getNumCars();
  }
  /**
   * Protobuf type {@code justine.robocar.TrafficStateHeader}
   */
  public static final class TrafficStateHeader extends
      com.google.protobuf.GeneratedMessage
      implements TrafficStateHeaderOrBuilder {
    // Use TrafficStateHeader.newBuilder() to construct.
    private TrafficStateHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TrafficStateHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TrafficStateHeader defaultInstance;
    public static TrafficStateHeader getDefaultInstance() {
      return defaultInstance;
    }

    public TrafficStateHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TrafficStateHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timeMinutes_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timeElapsed_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              numCars_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return justine.robocar.TrafficStateProtos.internal_static_justine_robocar_TrafficStateHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return justine.robocar.TrafficStateProtos.internal_static_justine_robocar_TrafficStateHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              justine.robocar.TrafficStateProtos.TrafficStateHeader.class, justine.robocar.TrafficStateProtos.TrafficStateHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<TrafficStateHeader> PARSER =
        new com.google.protobuf.AbstractParser<TrafficStateHeader>() {
      public TrafficStateHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrafficStateHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TrafficStateHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 time_minutes = 1;
    public static final int TIME_MINUTES_FIELD_NUMBER = 1;
    private int timeMinutes_;
    /**
     * <code>required int32 time_minutes = 1;</code>
     */
    public boolean hasTimeMinutes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 time_minutes = 1;</code>
     */
    public int getTimeMinutes() {
      return timeMinutes_;
    }

    // required int32 time_elapsed = 2;
    public static final int TIME_ELAPSED_FIELD_NUMBER = 2;
    private int timeElapsed_;
    /**
     * <code>required int32 time_elapsed = 2;</code>
     */
    public boolean hasTimeElapsed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 time_elapsed = 2;</code>
     */
    public int getTimeElapsed() {
      return timeElapsed_;
    }

    // required int32 num_cars = 3;
    public static final int NUM_CARS_FIELD_NUMBER = 3;
    private int numCars_;
    /**
     * <code>required int32 num_cars = 3;</code>
     */
    public boolean hasNumCars() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 num_cars = 3;</code>
     */
    public int getNumCars() {
      return numCars_;
    }

    private void initFields() {
      timeMinutes_ = 0;
      timeElapsed_ = 0;
      numCars_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTimeMinutes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeElapsed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumCars()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, timeMinutes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, timeElapsed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, numCars_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timeMinutes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, timeElapsed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, numCars_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static justine.robocar.TrafficStateProtos.TrafficStateHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static justine.robocar.TrafficStateProtos.TrafficStateHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static justine.robocar.TrafficStateProtos.TrafficStateHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static justine.robocar.TrafficStateProtos.TrafficStateHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static justine.robocar.TrafficStateProtos.TrafficStateHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static justine.robocar.TrafficStateProtos.TrafficStateHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static justine.robocar.TrafficStateProtos.TrafficStateHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static justine.robocar.TrafficStateProtos.TrafficStateHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static justine.robocar.TrafficStateProtos.TrafficStateHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static justine.robocar.TrafficStateProtos.TrafficStateHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(justine.robocar.TrafficStateProtos.TrafficStateHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code justine.robocar.TrafficStateHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements justine.robocar.TrafficStateProtos.TrafficStateHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return justine.robocar.TrafficStateProtos.internal_static_justine_robocar_TrafficStateHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return justine.robocar.TrafficStateProtos.internal_static_justine_robocar_TrafficStateHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                justine.robocar.TrafficStateProtos.TrafficStateHeader.class, justine.robocar.TrafficStateProtos.TrafficStateHeader.Builder.class);
      }

      // Construct using justine.robocar.TrafficStateProtos.TrafficStateHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timeMinutes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timeElapsed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        numCars_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return justine.robocar.TrafficStateProtos.internal_static_justine_robocar_TrafficStateHeader_descriptor;
      }

      public justine.robocar.TrafficStateProtos.TrafficStateHeader getDefaultInstanceForType() {
        return justine.robocar.TrafficStateProtos.TrafficStateHeader.getDefaultInstance();
      }

      public justine.robocar.TrafficStateProtos.TrafficStateHeader build() {
        justine.robocar.TrafficStateProtos.TrafficStateHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public justine.robocar.TrafficStateProtos.TrafficStateHeader buildPartial() {
        justine.robocar.TrafficStateProtos.TrafficStateHeader result = new justine.robocar.TrafficStateProtos.TrafficStateHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timeMinutes_ = timeMinutes_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timeElapsed_ = timeElapsed_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.numCars_ = numCars_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof justine.robocar.TrafficStateProtos.TrafficStateHeader) {
          return mergeFrom((justine.robocar.TrafficStateProtos.TrafficStateHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(justine.robocar.TrafficStateProtos.TrafficStateHeader other) {
        if (other == justine.robocar.TrafficStateProtos.TrafficStateHeader.getDefaultInstance()) return this;
        if (other.hasTimeMinutes()) {
          setTimeMinutes(other.getTimeMinutes());
        }
        if (other.hasTimeElapsed()) {
          setTimeElapsed(other.getTimeElapsed());
        }
        if (other.hasNumCars()) {
          setNumCars(other.getNumCars());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimeMinutes()) {
          
          return false;
        }
        if (!hasTimeElapsed()) {
          
          return false;
        }
        if (!hasNumCars()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        justine.robocar.TrafficStateProtos.TrafficStateHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (justine.robocar.TrafficStateProtos.TrafficStateHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 time_minutes = 1;
      private int timeMinutes_ ;
      /**
       * <code>required int32 time_minutes = 1;</code>
       */
      public boolean hasTimeMinutes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 time_minutes = 1;</code>
       */
      public int getTimeMinutes() {
        return timeMinutes_;
      }
      /**
       * <code>required int32 time_minutes = 1;</code>
       */
      public Builder setTimeMinutes(int value) {
        bitField0_ |= 0x00000001;
        timeMinutes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 time_minutes = 1;</code>
       */
      public Builder clearTimeMinutes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeMinutes_ = 0;
        onChanged();
        return this;
      }

      // required int32 time_elapsed = 2;
      private int timeElapsed_ ;
      /**
       * <code>required int32 time_elapsed = 2;</code>
       */
      public boolean hasTimeElapsed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 time_elapsed = 2;</code>
       */
      public int getTimeElapsed() {
        return timeElapsed_;
      }
      /**
       * <code>required int32 time_elapsed = 2;</code>
       */
      public Builder setTimeElapsed(int value) {
        bitField0_ |= 0x00000002;
        timeElapsed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 time_elapsed = 2;</code>
       */
      public Builder clearTimeElapsed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timeElapsed_ = 0;
        onChanged();
        return this;
      }

      // required int32 num_cars = 3;
      private int numCars_ ;
      /**
       * <code>required int32 num_cars = 3;</code>
       */
      public boolean hasNumCars() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 num_cars = 3;</code>
       */
      public int getNumCars() {
        return numCars_;
      }
      /**
       * <code>required int32 num_cars = 3;</code>
       */
      public Builder setNumCars(int value) {
        bitField0_ |= 0x00000004;
        numCars_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num_cars = 3;</code>
       */
      public Builder clearNumCars() {
        bitField0_ = (bitField0_ & ~0x00000004);
        numCars_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:justine.robocar.TrafficStateHeader)
    }

    static {
      defaultInstance = new TrafficStateHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:justine.robocar.TrafficStateHeader)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_justine_robocar_CarData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_justine_robocar_CarData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_justine_robocar_TrafficStateHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_justine_robocar_TrafficStateHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021src/robocar.proto\022\017justine.robocar\"\232\002\n" +
      "\007CarData\022\021\n\tnode_from\030\001 \002(\006\022\017\n\007node_to\030\002" +
      " \002(\006\022\020\n\010max_step\030\003 \002(\006\022\014\n\004step\030\004 \002(\006\0223\n\004" +
      "type\030\005 \002(\0162%.justine.robocar.CarData.Pro" +
      "toCarType\022\016\n\006caught\030\006 \001(\005\022\014\n\004team\030\007 \001(\t\022" +
      "\n\n\002id\030\010 \001(\005\022\014\n\004size\030\t \001(\005\022\014\n\004path\030\n \003(\006\"" +
      "P\n\014ProtoCarType\022\n\n\006NORMAL\020\000\022\n\n\006POLICE\020\001\022" +
      "\014\n\010GANGSTER\020\002\022\n\n\006CAUGHT\020\003\022\016\n\nPEDESTRIAN\020" +
      "\004\"R\n\022TrafficStateHeader\022\024\n\014time_minutes\030" +
      "\001 \002(\005\022\024\n\014time_elapsed\030\002 \002(\005\022\020\n\010num_cars\030",
      "\003 \002(\005B%\n\017justine.robocarB\022TrafficStatePr" +
      "otos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_justine_robocar_CarData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_justine_robocar_CarData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_justine_robocar_CarData_descriptor,
              new java.lang.String[] { "NodeFrom", "NodeTo", "MaxStep", "Step", "Type", "Caught", "Team", "Id", "Size", "Path", });
          internal_static_justine_robocar_TrafficStateHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_justine_robocar_TrafficStateHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_justine_robocar_TrafficStateHeader_descriptor,
              new java.lang.String[] { "TimeMinutes", "TimeElapsed", "NumCars", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
